print error message in InteractionHandler
dkdeploy/dkdeploy-core pull request #4
Opened 2016-07-14 09:08 UTC by klyonrad

The InteractionHandler was simply swallowing any error messages, for example error codes that were sent from server.

2017-04-07 10:20 UTC, websi requested changes

2017-04-07 10:20 UTC, websi commented on lib/dkdeploy/interaction_handler/mysql.rb
> +          @mysql_error_seen = true if data =~ /.*ERROR.*/i
Do we need this logik at this point?
Can we simplify that and output all the stream information here?
What types of information can happen here?

2017-07-04 12:32 UTC, klyonrad commented
simply rebased on new `develop` branch

2017-10-12 14:00 UTC, websi commented
New pull request #36

2017-10-12 14:00 UTC, closed without merging